### ISSUE TITLE
Magical Chase crashes after selecting difficulty sometimes

### ISSUE THREAD

**Issue by MiRIr** [MiSTer-devel/TurboGrafx16_MiSTer#25] opened 2018-10-04 07:47 UTC
This applies to both the USA and Japanese versions of the game.

I have found a way to crash the game somewhat reliably. Here is the easiest way to reproduce it:

- Turn on Auto Fire 100ms for the Run button
- Start the game
- Hold down the Run button
- Keep holding down the Run button until the game crashes, which should be after you selected the Breeze difficulty and before the game should actually start

If it didn't crash, which can happen, you can simply reset and try again. It happened the first time I tried the game. It may take a few resets for you.

Here's some other info you may be interested in:

- ROM Data Swap: No
- Sprites per line: Std(16)
- ROM Storage: DDR3
- Turbo Tap: Enabled
- Controller Buttons: 2

**Comment by cr4zymanz0r** [comment] 2018-11-04 19:38
I ran into this issue too on the 20180925 core. I couldn't get to trigger every time, but I probably could around half the time.

**Comment by dshadoff** [comment] 2020-02-20 12:50
Please verify whether this issue still exists on new release -> Release 20200220

**Comment by cr4zymanz0r** [comment] 2020-02-28 01:00
I tried several times to try to trigger the crash and I'm not running into issues now. I recommend closing this issue.

**Comment by MiRIr** [comment] 2020-02-28 08:44
Thanks for testing it out @cr4zymanz0r , closing this now.

**Comment by bootsector** [comment] 2020-12-07 09:06
I've just ran into this issue in the latest version of the core! Regression bug?

**Comment by matthargett** [comment] 2020-12-07 21:20
Here's a video of my repro case: https://www.youtube.com/watch?v=oZzUJPBkO8U
Happy to try anything else to provide enough info for it to get fixed. Thanks for all your work to date! :)

**Comment by matthargett** [comment] 2020-12-08 18:08
my setup: they are alliance AS4C32M16SB-7TIN (it's the 128mb model). it's SDRAM

**Comment by bootsector** [comment] 2020-12-20 01:35
I couldn't reproduce this issue anymore since the last commit. It seems fixed to me now.

**Closed** 2020-12-20 05:17 UTC
