### ISSUE TITLE
Is the left and right channels of cd audio reversed?

### ISSUE THREAD

**Issue by szuping** [MiSTer-devel/TurboGrafx16_MiSTer#199] opened 2023-11-12 13:37 UTC
Hello everyone, has anyone tested whether the left and right channels of the CD AUDIO/GAME are reversed? I think the left and right channels of the CD AUDIO/GAME seem to be reversed? Is this a core problem? (Tested using 240P-TEST .pce/cue, and using a special left mono/right mono music CD)

**Comment by szuping** [comment] 2023-11-12 14:45
I used 240P to test first to confirm that the hardware channel was correct, and then used CD-AUDIO's cue/bin to test. In the MISTER-PCE-CORE-music player, It seems to show wrong channels with wrong playback...

 I made a self-made CD for testing. There are two songs, the first one only has the left channel(Track 1). The second song has only the right channel(Track 2), but when played in the current PCE-CORE, it will display the left channel of the first song as the right channel, and the right channel of the second song as the left channel, and so on Play.

**Comment by szuping** [comment] 2023-11-12 14:46
![2-R](https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/assets/150599431/02616096-4604-4e03-8bd9-44aaa57b8d83)
![1-L](https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/assets/150599431/321af510-3d81-4474-921b-6a2385890681)

**Comment by szuping** [comment] 2023-11-12 15:28
https://drive.google.com/drive/folders/1WChvxhoSXK-d7Ajr-uNdF6Qhgw2ils0J?usp=sharing

use [BIOS] Super CD-ROM System (Japan) (v3.0).pce

**Comment by dshadoff** [comment] 2023-11-12 15:58
I have confirmed that the VU meter is showing the wrong channel on MiSTer, compared to real hardware.
However, I don't have my MiSTer connected to a stereo so I can't verify the sound ouput myself.

The user "Call me Tim, Tim the Enchanter" on discord verified that HDMI sound output is normal on his system (but confirmation about other sound outputs have not been made).

I'm pretty sure the VU meter is driven by separate signals, so I will look into that area.

**Comment by dshadoff** [comment] 2023-11-16 16:06
I requested Artemio to add a function to 240P Test Suite to clearly check L/R channels for CD audio, and to validate MiSTer outputs.  Version 1.14 (15/11/2023) of 240P Test Suite has this feature.

Additionally, he said this about the results of his testing:

> Tested on an original briefcase, all stock with the latest 240p test suite and against MiSTer FPGA via all audio outputs, they all match in left right consistency. tested direct optical, HDMI and direct analog.

Based on this, there seems to be no issue with the delivery of audio; it's only the data fed to the VU meters.  I have a fix for this, and will submit a PR today.

**Comment by dshadoff** [comment] 2023-12-04 18:19
This should now be closed, as the new release (Dec 4, 2023) includes this fix.

**Closed** 2023-12-05 12:54 UTC
