### ISSUE TITLE
Dauntaun Nekketsu Monogatari [NXCD3019] not loading with SYSCARD v3.01 (U) 

### ISSUE THREAD

**Issue by tlaloc-q** [MiSTer-devel/TurboGrafx16_MiSTer#101] opened 2020-05-27 05:06 UTC
Downtown Nekketsu Monogatari [NXCD3019] is not loading and shows what appears to be a SUPER CD-ROM2 'warning' screen, no matter whether I try SYSCARD v3.01 (U)/'cd_bios.rom' with Arcade Card mode ON or OFF.

Downtown Nekketsu Monogatari was also known as River City Ransom (SCD).

**Comment by sorgelig** [comment] 2020-05-27 08:10
Most japanese games require japanese bios. 
It's not a bug.

**Comment by tlaloc-q** [comment] 2020-05-27 08:28
Funny, it worked on Magic Engine with the US Bios and to let you know, on real hardware there was never any real regional copy protection for these PC-Engine CD games, so having something like a Turbo Duo would allow you to play most every japanese game I threw at it.
Without being able to verify this on actual hardware, I must admit that I found that it worked after placing SYSCARD3.0(J) in there as cd_bios.rom, but it is unusual that an emulator like Magic Engine would allow me to play Downtown Nekketsu Monogatari with a US bios yet MiSTer's TGFX16 core wouldn't.

**Comment by sorgelig** [comment] 2020-05-27 08:33
MiSTer is not emulator.
Also MiSTer doesn't mimic any emulator and doesn't use tricks to bypass BIOS version check.

**Comment by tlaloc-q** [comment] 2020-05-27 08:48
I'm trying to help, as I know that this is MiSTer is NOT on emulator in that it's goal is cycle accuracy and faithful replication of original hardware. I feel strongly that in this instance you may be mistaken in your presumption that a majority of japanese games required a japanese bios. I used to own a US bios equipped non-modded Turbo Duo and have NEVER run into a single japanese game I could not play with my v3.01 US BIOS. If the aim is faithful replication of original hardware and accuracy, then I'm simply trying to help in that endeavor. Thank you for your time.

**Comment by dshadoff** [comment] 2020-05-28 16:21
I have tested and found different behavior on hardware compared to MiSTer.
This is likely to also likely to be reported on other games which work fine on US hardware with US BIOS.
Note: There are only a couple of games which won't run on a US machine; A.III is one of them

The reason why Downtown Nekketsu is failing seems to be because the memory is mapped via hardware in the region of $18Cx:

Registers $18C0..$18C3 are for the internal SCD memory built into the Duo & SuperCDROM2 hardware.

Registers $18C5..$18C7 are for the external SCD memory built into the Japanese and US Super System Cards.

The hardware in the US Super System Card is identical to the hardware in the Japanese Super System Card, and so reading any ports on the card will give reversed bits because of the swapping of the data lines on the US cartridge port.

That's why the Turbografx Super System Card checks $18C5/$18C6 for $55 & $AA, instead of Japanese Super System Card checking for $AA & $55.

It also explains what ex_memopen is returning in the X register, and *why* it sets bit 7 of X if it detects internal memory.

The value in bits 0..6 of X is the amount of SCD memory in 64Kbyte increments.

Bit 7 is used to differentiate whether a Duo/SuperCDROM2 has found SCD memory in a cartridge (from $18C5..$18C7) or in internal memory (from $18C1..$18C3), so that it doesn't unlock the internal memory if it is using external memory instead.

**Comment by Left-Empty** [comment] 2020-05-28 16:46
Throwing in there (although you are probably aware), that somebody reported [a similar issue with Star Parodier on the forums(https://misterfpga.org/viewtopic.php?f=19&t=205)]

**Comment by sorgelig** [comment] 2020-05-28 17:27
i don't know about v3.01 (it seems some hacked version), but with original USA 3.0 BIOS i have trhe same warning screen in Mednafen.

**Comment by sorgelig** [comment] 2020-05-28 18:05
Ok, it seems fixed. New release will require correct not pre-swapped US BIOS.

**Comment by bootsector** [comment] 2020-05-28 18:45
Any real benefits on using USA 3.01 bios instead of the recommended one?

**Comment by sorgelig** [comment] 2020-05-28 18:52
i don't know any

**Comment by dshadoff** [comment] 2020-05-28 18:57
"3.01" BIOS was a fix to prevent bus conflicts between TurboEverdrive and TurboDuo occupying the same address range with memory on both.  It should NOT be used on MiSTer.

**Comment by bootsector** [comment] 2020-05-28 18:59
Thanks for answering, guys! I will make sure to keep away from that one!

**Comment by Left-Empty** [comment] 2020-05-28 18:59
Damn, that's a really stupid naming they chose. Most users are gonna rush for the higher version as default.

**Comment by sorgelig** [comment] 2020-05-28 19:08
actually hacked BIOS with autostart is the best for MiSTer. 
Basically you don't need startup screen for MiSTer. MiSTer has format Backup RAM option in OSD. Thus you don't have to care the language of BIOS.

**Comment by sorgelig** [comment] 2020-05-29 11:29
fixed in today's release

**Closed** 2020-06-01 18:31 UTC
