### ISSUE TITLE
6 Button, Turbo fire original controller support via SNAC

### ISSUE THREAD

**Issue by Brettster247** [MiSTer-devel/TurboGrafx16_MiSTer#116] opened 2020-08-10 15:33 UTC
While using SNAC adapters only buttons I and II work, the turbofire switches do not function and the official 6 button controller is only seen as a 2 button controller in Street fighter II Champion Edition despite which mode it's set to.

A better explanation here https://github.com/dshadoff/MiSTer_PCE-SNAC

Can the core be updated to provide faster pulses to allow the support chips in the PC Engine controllers to have this functionality? 

Thank you

**Comment by sorgelig** [comment] 2020-08-10 17:42
if i remember right, the problem is in HW making the pulse for controller. Basic pullup resistors used in USER_IO port is not enough. It requires a buffer element to provide correct pulse.

**Comment by dshadoff** [comment] 2020-08-10 17:58
This is not something which can be fixed in the core without changing the design assumption of the the SNAC port being open-collector.

I designed the adapter you referenced above in order to maintain that design goal, especially since all SNAC I/O requires an interface board of some sort anyway.

**Closed** 2020-08-11 09:20 UTC
